name: Publish Maven Package

on: push

env:
  MAIN_VER: 1

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set package version
      run: echo "::set-env name=PACKAGE_VERSION::${{ env.MAIN_VER }}.${{ github.run_number }}.$(date +"%y%m%d")"

#    - name: Publish to GitHub Packages Apache Maven
#      run: |
#        mvn release:update-versions
#        mvn deploy -s settings.xml
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: '9.0.4'
        java-package: jdk
        architecture: x64

    - name: Publish to GitHub Packages
      run: |
        sed -i 's/PACKAGE_VERSION/${{ env.PACKAGE_VERSION }}/g' pom.xml
        mvn deploy -s settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: check settings-security.xml - 01
      run: ls -R $HOME

    - name: set the master password
      run: mvn --encrypt-master-password 'test@pwd'

    - name: check settings-security.xml - 02
      run: ls -R $HOME
