name: Publish Maven Package

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s .m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
